stages:
    - build

build:
    stage: build
    before_script:
        - apt update
        - apt install -y cmake g++ extra-cmake-modules qt5-qmake qtbase5-dev qtdeclarative5-dev libkf5auth-dev libkf5completion-dev libkf5config-dev libkf5coreaddons-dev libkf5configwidgets-dev libkf5dbusaddons-dev libkf5doctools-dev libkf5i18n-dev libkf5iconthemes-dev libkf5jobwidgets-dev libkf5kio-dev libkf5notifications-dev libkf5solid-dev libkf5wallet-dev libkf5widgetsaddons-dev libkf5windowsystem-dev libkf5xmlgui-dev libkf5crash-dev libkf5dnssd-dev
    script:
        - echo "Building Smb4K"
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_WS_DISCOVERY=OFF -DINSTALL_PLASMOID=OFF -DINSTALL_HEADER_FILES=OFF ..
        - make