# SPDX-FileCopyrightText: 2021 Alexander Reinholdt <alexander.reinholdt@kdemail.net>
# SPDX-License-Identifier: CC0-1.0

include:
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/linux.yml
#  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/freebsd.yml

#  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-before.yml
#  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-applications-linux.yml
#  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-applications-freebsd.yml


