/***************************************************************************
    smb4kbasicnetworkitem  -  This class provides the basic network item
    for the core library of Smb4K.
                             -------------------
    begin                : Do Apr 2 2009
    copyright            : (C) 2009 by Alexander Reinholdt
    email                : dustpuppy@users.berlios.de
 ***************************************************************************/

/***************************************************************************
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful, but   *
 *   WITHOUT ANY WARRANTY; without even the implied warranty of            *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU     *
 *   General Public License for more details.                              *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,   *
 *   MA  02111-1307 USA                                                    *
 ***************************************************************************/

#ifndef SMB4KBASICNETWORKITEM_H
#define SMB4KBASICNETWORKITEM_H

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

// Qt includes
#include <QString>
#include <QIcon>
#include <QUrl>

// KDE includes
#include <kdemacros.h>

class KDE_EXPORT Smb4KBasicNetworkItem
{
  public:
    /**
     * Enumeration to determine the type of the network
     * item.
     *
     * @enum Workgroup      The network item is a workgroup or domain.
     * @enum Host           The network item is a host.
     * @enum Share          The network item is a share.
     * @enum Unknown        The network item type is unknown.
     */
    enum Type { 
      Workgroup,
      Host,
      Share,
      Unknown };

    /**
     * The constructor
     */
    Smb4KBasicNetworkItem( Smb4KBasicNetworkItem::Type type = Unknown );

    /**
     * The copy constructor
     */
    Smb4KBasicNetworkItem( const Smb4KBasicNetworkItem &item );

    /**
     * The destructor
     */
    ~Smb4KBasicNetworkItem();

    /**
     * This function returns the type of the basic network
     * item.
     *
     * @returns the type.
     */
    Type type() const { return m_type; }

    /**
     * With this function you can set a key, that can be used to identify
     * a certain network item.
     *
     * @param key           The key
     */
    void setKey( const QString &key );

    /**
     * This function returns the key for this network item. By default,
     * this is a random number that was generated by the constructor.
     *
     * @returns the identifying string for this item.
     */
    const QString &key() const { return m_key; }
    
    /**
     * This function sets the icon of the network item.
     * 
     * @param icon          The icon
     */
    void setIcon( const QIcon &icon );
    
    /**
     * This function returns the icon of the network item. By default, it
     * is the null icon. You must set the appropriate icon either in
     * a class that inherits this one or from somewhere else.
     * 
     * @returns the network item's icon.
     */
    const QIcon &icon() const { return m_icon; }

    /**
     * Sets the URL of the network item after some checks are passed.
     * 
     * @param url             The URL of the network item
     */
    void setURL( const QUrl &url );
    
    /**
     * Returns the URL (the full UNC) of the network item or an empty URL
     * if the network item does not have an URL (like a workgroup).
     * 
     * There is no setURL() function, because only derived classes should
     * be able to set the URL. Use the protected item_url object to set the 
     * URL in your derived class.
     * 
     * @returns the URL of the network item.
     */
    const QUrl &url() const { return item_url; }
    
  protected:
    /**
     * The URL
     */
    QUrl item_url;

  private:
    /**
     * The type
     */
    Type m_type;

    /**
     * The key
     */
    QString m_key;
    
    /**
     * The icon
     */
    QIcon m_icon;
};

#endif
